### ISSUE TITLE
Add fallback mechanism in v2

### ISSUE THREAD

**Issue by novln** [ulule/makroud#26]
Using multiple connections, define a fallback mechanism in case of a connexion error.

Example: https://github.com/ulule/ulule-api/blob/dev/pkg/core/store/gorm/store/retry.go

```
 Slave:
     Port: 5432
     Host: "local.okpal.com"
     User: "okpal"
     Password: "okpal"
     Name: "okpal"
     SSLmode: "disable"
     MaxIdleConnections: 20
     MaxOpenConnections: 50
     Fallback: "Master"
```
